packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@tmcw/togeojson': ^7.0.0
  '@types/geojson': ^7946.0.16
  '@types/xmldom': ^0.1.34
  '@vitejs/plugin-vue': ^5.2.1
  '@vue/tsconfig': ^0.7.0
  geojson: ^0.5.0
  rollup: ^4.37.0
  rollup-plugin-gpx: catalog
  vue: ^3.5.13
  vue-tsc: ^2.2.4
  xmldom: ^0.6.0
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
